kind: Service
apiVersion: v1
metadata:
  name: jupyter-app
  namespace: jupyter
spec:
  selector:
    app: jupyter-app
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-app-nodeport
  namespace: jupyter
spec:
  type: NodePort
  selector:
    app: jupyter-app
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30080
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1
kind: Deployment
metadata:
  name: jupyter-app
  namespace: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      name: jupyter-app
      labels:
        app: jupyter-app
    spec:
      containers:
      - name: jupyter-app
        image: jupyter/base-notebook
        ports:
        - containerPort: 8888